### ISSUE TITLE
[TODO] CI/CD 환경 구축

### ISSUE THREAD

**Issue by uowol** [uowol/Chzzk-Data-Analytics#6]
### Due
- TBD

### Todo-List
- [ ] PR 시 주어진 테스트 파이프라인을 따라 무결성을 검증하는 CI를 추가한다.
- [ ] 현재 버전의 Docker 이미지를 배포하는 CD를 추가한다.

### Example
```yaml
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Docker 이미지 빌드
      - run: docker build -t myapp:latest .

      # (옵션) 테스트
      - run: docker run myapp:latest pytest

      # (옵션) DockerHub or ECR로 push
      - run: docker push myrepo/myapp:latest
```
